@tool
extends Node3D
class_name Level

static var object_list = {
	"algae": {
		"unit_type": "object",
		"tags": ["water", "plant", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 15,
		"base_color": Vector2i(5, 2),
	},
	"text_algae": {
		"unit_type": "text",
		"tags": ["water", "plant", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(5, 0),
		"active_color": Vector2i(5, 1),
	},
	"baba": {
		"unit_type": "object",
		"tags": ["animal", "common"],
		"tiling": 2,
		"text_type": 0,
		"layer": 18,
		"base_color": Vector2i(0, 3),
	},
	"text_baba": {
		"unit_type": "text",
		"tags": ["animal", "common"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(4, 0),
		"active_color": Vector2i(4, 1),
	},
	"bat": {
		"unit_type": "object",
		"tags": ["cave", "animal"],
		"tiling": 4,
		"text_type": 0,
		"layer": 14,
		"base_color": Vector2i(3, 1),
	},
	"text_bat": {
		"unit_type": "text",
		"tags": ["cave", "animal"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(3, 0),
		"active_color": Vector2i(3, 1),
	},
	"belt": {
		"unit_type": "object",
		"tags": ["common", "machine", "movement"],
		"tiling": 3,
		"text_type": 0,
		"layer": 9,
		"base_color": Vector2i(1, 2),
	},
	"text_belt": {
		"unit_type": "text",
		"tags": ["common", "machine", "movement"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(1, 2),
		"active_color": Vector2i(1, 3),
	},
	"bird": {
		"unit_type": "object",
		"tags": ["mountain", "animal", "sky"],
		"tiling": 0,
		"text_type": 0,
		"layer": 17,
		"base_color": Vector2i(2, 3),
	},
	"text_bird": {
		"unit_type": "text",
		"tags": ["mountain", "animal", "sky"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(2, 2),
		"active_color": Vector2i(2, 3),
	},
	"text_w": {
		"unit_type": "text",
		"tags": ["text_letter"],
		"tiling": -1,
		"text_type": 5,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"bog": {
		"unit_type": "object",
		"tags": ["obstacle", "forest"],
		"tiling": 1,
		"text_type": 0,
		"layer": 2,
		"base_color": Vector2i(5, 1),
	},
	"text_bog": {
		"unit_type": "text",
		"tags": ["obstacle", "forest"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(5, 1),
		"active_color": Vector2i(5, 3),
	},
	"bolt": {
		"unit_type": "object",
		"tags": ["machine", "sky", "danger"],
		"tiling": 0,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(2, 4),
	},
	"text_bolt": {
		"unit_type": "text",
		"tags": ["machine", "sky", "danger"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(2, 3),
		"active_color": Vector2i(2, 4),
	},
	"box": {
		"unit_type": "object",
		"tags": ["common", "machine", "item", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(6, 2),
	},
	"text_box": {
		"unit_type": "text",
		"tags": ["common", "machine", "item", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(6, 0),
		"active_color": Vector2i(6, 1),
	},
	"brick": {
		"unit_type": "object",
		"tags": ["ruins", "floor", "decorative", "town"],
		"tiling": 1,
		"text_type": 0,
		"layer": 10,
		"base_color": Vector2i(6, 3),
	},
	"text_brick": {
		"unit_type": "text",
		"tags": ["ruins", "floor", "decorative", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(6, 0),
		"active_color": Vector2i(6, 1),
	},
	"bubble": {
		"unit_type": "object",
		"tags": ["water", "decorative"],
		"tiling": 4,
		"text_type": 0,
		"layer": 12,
		"base_color": Vector2i(1, 4),
	},
	"text_bubble": {
		"unit_type": "text",
		"tags": ["water", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(1, 3),
		"active_color": Vector2i(1, 4),
	},
	"bug": {
		"unit_type": "object",
		"tags": ["forest", "animal"],
		"tiling": 0,
		"text_type": 0,
		"layer": 17,
		"base_color": Vector2i(6, 2),
	},
	"text_bug": {
		"unit_type": "text",
		"tags": ["forest", "animal"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(6, 0),
		"active_color": Vector2i(6, 2),
	},
	"cake": {
		"unit_type": "object",
		"tags": ["item", "decorative", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 17,
		"base_color": Vector2i(4, 2),
	},
	"text_cake": {
		"unit_type": "text",
		"tags": ["item", "decorative", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(4, 1),
		"active_color": Vector2i(4, 2),
	},
	"cash": {
		"unit_type": "object",
		"tags": ["item", "danger", "decorative", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 12,
		"base_color": Vector2i(5, 2),
	},
	"text_cash": {
		"unit_type": "text",
		"tags": ["item", "danger", "decorative", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(5, 1),
		"active_color": Vector2i(5, 3),
	},
	"cliff": {
		"unit_type": "object",
		"tags": ["cave", "obstacle"],
		"tiling": 1,
		"text_type": 0,
		"layer": 14,
		"base_color": Vector2i(6, 1),
	},
	"text_cliff": {
		"unit_type": "text",
		"tags": ["cave", "obstacle"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(6, 0),
		"active_color": Vector2i(6, 2),
	},
	"cloud": {
		"unit_type": "object",
		"tags": ["sky", "obstacle"],
		"tiling": 1,
		"text_type": 0,
		"layer": 14,
		"base_color": Vector2i(1, 4),
	},
	"text_cloud": {
		"unit_type": "text",
		"tags": ["sky", "obstacle"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(1, 3),
		"active_color": Vector2i(1, 4),
	},
	"cog": {
		"unit_type": "object",
		"tags": ["machine", "item", "decorative"],
		"tiling": 4,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(0, 1),
	},
	"text_cog": {
		"unit_type": "text",
		"tags": ["machine", "item", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 2),
	},
	"crab": {
		"unit_type": "object",
		"tags": ["water", "animal"],
		"tiling": 0,
		"text_type": 0,
		"layer": 17,
		"base_color": Vector2i(2, 2),
	},
	"text_crab": {
		"unit_type": "text",
		"tags": ["water", "animal"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(2, 1),
		"active_color": Vector2i(2, 2),
	},
	"cup": {
		"unit_type": "object",
		"tags": ["item", "decorative", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 13,
		"base_color": Vector2i(1, 3),
	},
	"text_cup": {
		"unit_type": "text",
		"tags": ["item", "decorative", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(1, 2),
		"active_color": Vector2i(1, 3),
	},
	"cursor": {
		"unit_type": "object",
		"tags": ["common"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(4, 2),
	},
	"door": {
		"unit_type": "object",
		"tags": ["common", "obstacle", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 15,
		"base_color": Vector2i(2, 2),
	},
	"text_door": {
		"unit_type": "text",
		"tags": ["common", "obstacle", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(2, 1),
		"active_color": Vector2i(2, 2),
	},
	"dot": {
		"unit_type": "object",
		"tags": ["abstract", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 12,
		"base_color": Vector2i(0, 3),
	},
	"text_dot": {
		"unit_type": "text",
		"tags": ["abstract", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"dust": {
		"unit_type": "object",
		"tags": ["sky", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 12,
		"base_color": Vector2i(6, 2),
	},
	"text_dust": {
		"unit_type": "text",
		"tags": ["sky", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(6, 2),
		"active_color": Vector2i(2, 4),
	},
	"fence": {
		"unit_type": "object",
		"tags": ["autumn", "obstacle", "town"],
		"tiling": 1,
		"text_type": 0,
		"layer": 14,
		"base_color": Vector2i(6, 1),
	},
	"text_fence": {
		"unit_type": "text",
		"tags": ["autumn", "obstacle", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(6, 0),
		"active_color": Vector2i(6, 1),
	},
	"fire": {
		"unit_type": "object",
		"tags": ["cave", "decorative", "danger"],
		"tiling": -1,
		"text_type": 0,
		"layer": 15,
		"base_color": Vector2i(2, 3),
	},
	"text_fire": {
		"unit_type": "text",
		"tags": ["cave", "decorative", "danger"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(2, 0),
		"active_color": Vector2i(2, 2),
	},
	"flag": {
		"unit_type": "object",
		"tags": ["common", "item"],
		"tiling": -1,
		"text_type": 0,
		"layer": 17,
		"base_color": Vector2i(2, 4),
	},
	"text_flag": {
		"unit_type": "text",
		"tags": ["common", "item"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(6, 1),
		"active_color": Vector2i(2, 4),
	},
	"flower": {
		"unit_type": "object",
		"tags": ["plant", "forest", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 12,
		"base_color": Vector2i(3, 3),
	},
	"text_flower": {
		"unit_type": "text",
		"tags": ["plant", "forest", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(3, 2),
		"active_color": Vector2i(3, 3),
	},
	"foliage": {
		"unit_type": "object",
		"tags": ["autumn", "plant", "decorative", "floor"],
		"tiling": -1,
		"text_type": 0,
		"layer": 17,
		"base_color": Vector2i(6, 0),
	},
	"text_foliage": {
		"unit_type": "text",
		"tags": ["autumn", "plant", "decorative", "floor"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(2, 2),
		"active_color": Vector2i(2, 3),
	},
	"fruit": {
		"unit_type": "object",
		"tags": ["plant", "forest", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(2, 2),
	},
	"text_fruit": {
		"unit_type": "text",
		"tags": ["plant", "forest", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(2, 1),
		"active_color": Vector2i(2, 2),
	},
	"fungi": {
		"unit_type": "object",
		"tags": ["plant", "autumn", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 8,
		"base_color": Vector2i(6, 1),
	},
	"text_fungi": {
		"unit_type": "text",
		"tags": ["plant", "autumn", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(6, 0),
		"active_color": Vector2i(6, 2),
	},
	"fungus": {
		"unit_type": "object",
		"tags": ["plant", "autumn", "item", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(6, 1),
	},
	"text_fungus": {
		"unit_type": "text",
		"tags": ["plant", "autumn", "item", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(6, 0),
		"active_color": Vector2i(6, 1),
	},
	"ghost": {
		"unit_type": "object",
		"tags": ["autumn", "animal"],
		"tiling": 0,
		"text_type": 0,
		"layer": 17,
		"base_color": Vector2i(4, 2),
	},
	"text_ghost": {
		"unit_type": "text",
		"tags": ["autumn", "animal"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(4, 1),
		"active_color": Vector2i(4, 2),
	},
	"grass": {
		"unit_type": "object",
		"tags": ["plant", "forest", "floor"],
		"tiling": 1,
		"text_type": 0,
		"layer": 10,
		"base_color": Vector2i(5, 0),
	},
	"text_grass": {
		"unit_type": "text",
		"tags": ["plant", "forest", "floor"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(5, 1),
		"active_color": Vector2i(5, 3),
	},
	"hand": {
		"unit_type": "object",
		"tags": ["abstract"],
		"tiling": 0,
		"text_type": 0,
		"layer": 17,
		"base_color": Vector2i(3, 1),
	},
	"text_hand": {
		"unit_type": "text",
		"tags": ["abstract"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(3, 1),
		"active_color": Vector2i(4, 2),
	},
	"hedge": {
		"unit_type": "object",
		"tags": ["plant", "obstacle"],
		"tiling": 1,
		"text_type": 0,
		"layer": 14,
		"base_color": Vector2i(5, 1),
	},
	"text_hedge": {
		"unit_type": "text",
		"tags": ["plant", "obstacle"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(5, 0),
		"active_color": Vector2i(5, 1),
	},
	"husk": {
		"unit_type": "object",
		"tags": ["plant", "obstacle", "autumn"],
		"tiling": -1,
		"text_type": 0,
		"layer": 15,
		"base_color": Vector2i(6, 1),
	},
	"text_husk": {
		"unit_type": "text",
		"tags": ["plant", "obstacle", "autumn"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(5, 1),
		"active_color": Vector2i(6, 1),
	},
	"ice": {
		"unit_type": "object",
		"tags": ["mountain", "floor", "common"],
		"tiling": 1,
		"text_type": 0,
		"layer": 9,
		"base_color": Vector2i(1, 2),
	},
	"text_ice": {
		"unit_type": "text",
		"tags": ["mountain", "floor", "common"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(1, 2),
		"active_color": Vector2i(1, 3),
	},
	"jelly": {
		"unit_type": "object",
		"tags": ["water", "animal", "danger"],
		"tiling": -1,
		"text_type": 0,
		"layer": 17,
		"base_color": Vector2i(1, 4),
	},
	"text_jelly": {
		"unit_type": "text",
		"tags": ["water", "animal", "danger"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(1, 3),
		"active_color": Vector2i(1, 4),
	},
	"keke": {
		"unit_type": "object",
		"tags": ["common", "animal"],
		"tiling": 2,
		"text_type": 0,
		"layer": 18,
		"base_color": Vector2i(2, 2),
	},
	"text_keke": {
		"unit_type": "text",
		"tags": ["common", "animal"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(2, 1),
		"active_color": Vector2i(2, 2),
	},
	"key": {
		"unit_type": "object",
		"tags": ["common", "item", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(2, 4),
	},
	"text_key": {
		"unit_type": "text",
		"tags": ["common", "item", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(6, 1),
		"active_color": Vector2i(2, 4),
	},
	"ladder": {
		"unit_type": "object",
		"tags": ["item", "machine", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 10,
		"base_color": Vector2i(2, 3),
	},
	"text_ladder": {
		"unit_type": "text",
		"tags": ["item", "machine", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(2, 2),
		"active_color": Vector2i(2, 3),
	},
	"lava": {
		"unit_type": "object",
		"tags": ["obstacle", "cave", "danger"],
		"tiling": 1,
		"text_type": 0,
		"layer": 2,
		"base_color": Vector2i(2, 3),
	},
	"text_lava": {
		"unit_type": "text",
		"tags": ["obstacle", "cave", "danger"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(2, 2),
		"active_color": Vector2i(2, 3),
	},
	"leaf": {
		"unit_type": "object",
		"tags": ["plant", "autumn", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 8,
		"base_color": Vector2i(2, 4),
	},
	"text_leaf": {
		"unit_type": "text",
		"tags": ["plant", "autumn", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(6, 1),
		"active_color": Vector2i(2, 4),
	},
	"line": {
		"unit_type": "object",
		"tags": ["abstract", "common"],
		"tiling": 1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(0, 3),
	},
	"text_line": {
		"unit_type": "text",
		"tags": ["abstract", "common"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(0, 2),
		"active_color": Vector2i(0, 3),
	},
	"love": {
		"unit_type": "object",
		"tags": ["common", "abstract", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(4, 2),
	},
	"text_love": {
		"unit_type": "text",
		"tags": ["common", "abstract", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(4, 1),
		"active_color": Vector2i(4, 2),
	},
	"me": {
		"unit_type": "object",
		"tags": ["common", "animal"],
		"tiling": 2,
		"text_type": 0,
		"layer": 18,
		"base_color": Vector2i(3, 1),
	},
	"text_me": {
		"unit_type": "text",
		"tags": ["common", "animal"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(3, 0),
		"active_color": Vector2i(3, 1),
	},
	"moon": {
		"unit_type": "object",
		"tags": ["sky", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(2, 4),
	},
	"text_moon": {
		"unit_type": "text",
		"tags": ["sky", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(6, 1),
		"active_color": Vector2i(2, 4),
	},
	"orb": {
		"unit_type": "object",
		"tags": ["common", "item"],
		"tiling": -1,
		"text_type": 0,
		"layer": 17,
		"base_color": Vector2i(4, 1),
	},
	"text_orb": {
		"unit_type": "text",
		"tags": ["common", "item"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(4, 0),
		"active_color": Vector2i(4, 1),
	},
	"pillar": {
		"unit_type": "object",
		"tags": ["ruins", "obstacle"],
		"tiling": -1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(0, 1),
	},
	"text_pillar": {
		"unit_type": "text",
		"tags": ["ruins", "obstacle"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(1, 1),
		"active_color": Vector2i(0, 1),
	},
	"pipe": {
		"unit_type": "object",
		"tags": ["machine", "obstacle"],
		"tiling": 1,
		"text_type": 0,
		"layer": 14,
		"base_color": Vector2i(1, 1),
	},
	"text_pipe": {
		"unit_type": "text",
		"tags": ["machine", "obstacle"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(1, 1),
		"active_color": Vector2i(0, 1),
	},
	"reed": {
		"unit_type": "object",
		"tags": ["forest", "plant", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(6, 2),
	},
	"text_reed": {
		"unit_type": "text",
		"tags": ["forest", "plant", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(6, 1),
		"active_color": Vector2i(6, 2),
	},
	"robot": {
		"unit_type": "object",
		"tags": ["machine"],
		"tiling": 2,
		"text_type": 0,
		"layer": 17,
		"base_color": Vector2i(0, 1),
	},
	"text_robot": {
		"unit_type": "text",
		"tags": ["machine"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(1, 1),
		"active_color": Vector2i(0, 1),
	},
	"rocket": {
		"unit_type": "object",
		"tags": ["machine", "sky"],
		"tiling": 0,
		"text_type": 0,
		"layer": 15,
		"base_color": Vector2i(0, 1),
	},
	"text_rocket": {
		"unit_type": "text",
		"tags": ["machine", "sky"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(1, 1),
		"active_color": Vector2i(0, 1),
	},
	"rock": {
		"unit_type": "object",
		"tags": ["common", "item", "cave"],
		"tiling": -1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(6, 2),
	},
	"text_rock": {
		"unit_type": "text",
		"tags": ["common", "item", "cave"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(6, 0),
		"active_color": Vector2i(6, 1),
	},
	"rose": {
		"unit_type": "object",
		"tags": ["plant", "decorative", "forest"],
		"tiling": -1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(2, 2),
	},
	"text_rose": {
		"unit_type": "text",
		"tags": ["plant", "decorative", "forest"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(2, 1),
		"active_color": Vector2i(2, 2),
	},
	"rubble": {
		"unit_type": "object",
		"tags": ["mountain", "decorative", "floor"],
		"tiling": 1,
		"text_type": 0,
		"layer": 8,
		"base_color": Vector2i(6, 1),
	},
	"text_rubble": {
		"unit_type": "text",
		"tags": ["mountain", "decorative", "floor"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(6, 0),
		"active_color": Vector2i(6, 1),
	},
	"text_x": {
		"unit_type": "text",
		"tags": ["text_letter"],
		"tiling": -1,
		"text_type": 5,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"shirt": {
		"unit_type": "object",
		"tags": ["item", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 15,
		"base_color": Vector2i(2, 1),
	},
	"text_shirt": {
		"unit_type": "text",
		"tags": ["item", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(1, 1),
		"active_color": Vector2i(2, 1),
	},
	"skull": {
		"unit_type": "object",
		"tags": ["common", "danger"],
		"tiling": 0,
		"text_type": 0,
		"layer": 17,
		"base_color": Vector2i(2, 1),
	},
	"text_skull": {
		"unit_type": "text",
		"tags": ["common", "danger"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(2, 0),
		"active_color": Vector2i(2, 1),
	},
	"spike": {
		"unit_type": "object",
		"tags": ["mountain", "decorative", "danger"],
		"tiling": -1,
		"text_type": 0,
		"layer": 10,
		"base_color": Vector2i(1, 1),
	},
	"text_spike": {
		"unit_type": "text",
		"tags": ["mountain", "decorative", "danger"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(1, 1),
		"active_color": Vector2i(0, 1),
	},
	"star": {
		"unit_type": "object",
		"tags": ["sky", "decorative", "item"],
		"tiling": -1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(2, 4),
	},
	"text_star": {
		"unit_type": "text",
		"tags": ["sky", "decorative", "item"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(6, 1),
		"active_color": Vector2i(2, 4),
	},
	"statue": {
		"unit_type": "object",
		"tags": ["ruins", "decorative"],
		"tiling": 0,
		"text_type": 0,
		"layer": 17,
		"base_color": Vector2i(0, 1),
	},
	"text_statue": {
		"unit_type": "text",
		"tags": ["ruins", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 2),
	},
	"stump": {
		"unit_type": "object",
		"tags": ["ruins", "forest", "plant", "decorative", "obstacle"],
		"tiling": -1,
		"text_type": 0,
		"layer": 12,
		"base_color": Vector2i(6, 1),
	},
	"text_stump": {
		"unit_type": "text",
		"tags": ["ruins", "forest", "plant", "decorative", "obstacle"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(6, 0),
		"active_color": Vector2i(6, 2),
	},
	"sun": {
		"unit_type": "object",
		"tags": ["mountain", "decorative", "sky"],
		"tiling": -1,
		"text_type": 0,
		"layer": 14,
		"base_color": Vector2i(2, 4),
	},
	"text_sun": {
		"unit_type": "text",
		"tags": ["mountain", "decorative", "sky"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(2, 3),
		"active_color": Vector2i(2, 4),
	},
	"text_right": {
		"unit_type": "text",
		"tags": ["text_quality", "common", "movement"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(1, 3),
		"active_color": Vector2i(1, 4),
	},
	"text_up": {
		"unit_type": "text",
		"tags": ["text_quality", "common", "movement"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(1, 3),
		"active_color": Vector2i(1, 4),
	},
	"text_left": {
		"unit_type": "text",
		"tags": ["text_quality", "common", "movement"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(1, 3),
		"active_color": Vector2i(1, 4),
	},
	"text_down": {
		"unit_type": "text",
		"tags": ["text_quality", "common", "movement"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(1, 3),
		"active_color": Vector2i(1, 4),
	},
	"text_all": {
		"unit_type": "text",
		"tags": ["text_special"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_and": {
		"unit_type": "text",
		"tags": ["text_verb", "common"],
		"tiling": -1,
		"text_type": 6,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_best": {
		"unit_type": "text",
		"tags": ["text_quality", "decorative"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(2, 3),
		"active_color": Vector2i(2, 4),
	},
	"text_red": {
		"unit_type": "text",
		"tags": ["text_quality", "decorative", "colour"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(2, 1),
		"active_color": Vector2i(2, 2),
	},
	"text_blue": {
		"unit_type": "text",
		"tags": ["text_quality", "decorative", "colour"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(3, 2),
		"active_color": Vector2i(3, 3),
	},
	"text_green": {
		"unit_type": "text",
		"tags": ["text_quality", "decorative", "colour"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(5, 1),
		"active_color": Vector2i(5, 2),
	},
	"text_yellow": {
		"unit_type": "text",
		"tags": ["text_quality", "decorative", "colour"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(6, 1),
		"active_color": Vector2i(2, 4),
	},
	"text_purple": {
		"unit_type": "text",
		"tags": ["text_quality", "decorative", "colour"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(3, 0),
		"active_color": Vector2i(3, 1),
	},
	"text_pink": {
		"unit_type": "text",
		"tags": ["text_quality", "decorative", "colour"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(4, 0),
		"active_color": Vector2i(4, 1),
	},
	"text_grey": {
		"unit_type": "text",
		"tags": ["text_quality", "decorative", "colour"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(1, 1),
		"active_color": Vector2i(0, 1),
	},
	"text_black": {
		"unit_type": "text",
		"tags": ["text_quality", "decorative", "colour"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(1, 1),
		"active_color": Vector2i(0, 1),
	},
	"text_white": {
		"unit_type": "text",
		"tags": ["text_quality", "decorative", "colour"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_brown": {
		"unit_type": "text",
		"tags": ["text_quality", "decorative", "colour"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(2, 1),
		"active_color": Vector2i(6, 1),
	},
	"text_orange": {
		"unit_type": "text",
		"tags": ["text_quality", "decorative", "colour"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(2, 2),
		"active_color": Vector2i(2, 3),
	},
	"text_bonus": {
		"unit_type": "text",
		"tags": ["common", "text_quality", "text_special"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(4, 0),
		"active_color": Vector2i(4, 1),
	},
	"text_chill": {
		"unit_type": "text",
		"tags": ["text_quality", "movement"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(3, 2),
		"active_color": Vector2i(3, 3),
	},
	"text_cursor": {
		"unit_type": "text",
		"tags": ["text_special", "common"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(2, 3),
		"active_color": Vector2i(2, 4),
	},
	"text_defeat": {
		"unit_type": "text",
		"tags": ["text_quality", "danger"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(2, 0),
		"active_color": Vector2i(2, 1),
	},
	"text_eat": {
		"unit_type": "text",
		"tags": ["text_verb"],
		"tiling": -1,
		"text_type": 1,
		"layer": 20,
		"base_color": Vector2i(2, 1),
		"active_color": Vector2i(2, 2),
	},
	"text_empty": {
		"unit_type": "text",
		"tags": ["common", "abstract"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_end": {
		"unit_type": "text",
		"tags": ["text_quality", "text_special"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_facing": {
		"unit_type": "text",
		"tags": ["text_condition"],
		"tiling": -1,
		"text_type": 7,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
		"arg_extra": ["right", "up", "left", "down"],
	},
	"text_back": {
		"unit_type": "text",
		"tags": ["text_quality", "abstract", "text_special", "movement"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(4, 0),
		"active_color": Vector2i(4, 1),
	},
	"text_fall": {
		"unit_type": "text",
		"tags": ["text_quality", "sky", "movement"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(5, 1),
		"active_color": Vector2i(5, 3),
	},
	"text_fallright": {
		"unit_type": "text",
		"tags": ["text_quality", "sky", "movement"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(5, 1),
		"active_color": Vector2i(5, 3),
	},
	"text_fallup": {
		"unit_type": "text",
		"tags": ["text_quality", "sky", "movement"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(5, 1),
		"active_color": Vector2i(5, 3),
	},
	"text_fallleft": {
		"unit_type": "text",
		"tags": ["text_quality", "sky", "movement"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(5, 1),
		"active_color": Vector2i(5, 3),
	},
	"text_fear": {
		"unit_type": "text",
		"tags": ["text_verb", "danger", "movement"],
		"tiling": -1,
		"text_type": 1,
		"layer": 20,
		"base_color": Vector2i(2, 1),
		"active_color": Vector2i(2, 2),
	},
	"text_float": {
		"unit_type": "text",
		"tags": ["text_quality", "water"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(1, 2),
		"active_color": Vector2i(1, 4),
	},
	"text_follow": {
		"unit_type": "text",
		"tags": ["text_verb", "movement"],
		"tiling": -1,
		"text_type": 1,
		"layer": 20,
		"base_color": Vector2i(5, 1),
		"active_color": Vector2i(5, 3),
	},
	"text_group": {
		"unit_type": "text",
		"tags": ["common", "text_special"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(3, 2),
		"active_color": Vector2i(3, 3),
	},
	"text_has": {
		"unit_type": "text",
		"tags": ["text_verb", "common"],
		"tiling": -1,
		"text_type": 1,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_hide": {
		"unit_type": "text",
		"tags": ["text_quality", "text_special", "abstract"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(3, 2),
		"active_color": Vector2i(3, 3),
	},
	"text_hot": {
		"unit_type": "text",
		"tags": ["text_quality", "cave", "danger"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(2, 2),
		"active_color": Vector2i(2, 3),
	},
	"text_idle": {
		"unit_type": "text",
		"tags": ["text_condition", "text_prefix"],
		"tiling": -1,
		"text_type": 3,
		"layer": 20,
		"base_color": Vector2i(2, 2),
		"active_color": Vector2i(2, 3),
	},
	"text_is": {
		"unit_type": "text",
		"tags": ["text_verb", "common"],
		"tiling": -1,
		"text_type": 1,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
		"arg_type": [0, 2],
	},
	"text_level": {
		"unit_type": "text",
		"tags": ["text_special", "common"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(4, 0),
		"active_color": Vector2i(4, 1),
	},
	"text_lonely": {
		"unit_type": "text",
		"tags": ["text_condition", "text_prefix", "mountain"],
		"tiling": -1,
		"text_type": 3,
		"layer": 20,
		"base_color": Vector2i(2, 1),
		"active_color": Vector2i(2, 2),
	},
	"text_often": {
		"unit_type": "text",
		"tags": ["text_condition", "text_prefix", "abstract", "common"],
		"tiling": -1,
		"text_type": 3,
		"layer": 20,
		"base_color": Vector2i(5, 2),
		"active_color": Vector2i(5, 3),
	},
	"text_seldom": {
		"unit_type": "text",
		"tags": ["text_condition", "text_prefix", "abstract", "common"],
		"tiling": -1,
		"text_type": 3,
		"layer": 20,
		"base_color": Vector2i(3, 2),
		"active_color": Vector2i(3, 3),
	},
	"text_make": {
		"unit_type": "text",
		"tags": ["text_verb", "common"],
		"tiling": -1,
		"text_type": 1,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_melt": {
		"unit_type": "text",
		"tags": ["text_quality", "cave", "danger"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(1, 2),
		"active_color": Vector2i(1, 3),
	},
	"text_more": {
		"unit_type": "text",
		"tags": ["text_quality", "abstract", "common"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(4, 0),
		"active_color": Vector2i(4, 1),
	},
	"text_move": {
		"unit_type": "text",
		"tags": ["text_quality", "common", "movement"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(5, 1),
		"active_color": Vector2i(5, 3),
	},
	"text_near": {
		"unit_type": "text",
		"tags": ["text_condition", "common"],
		"tiling": -1,
		"text_type": 7,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_not": {
		"unit_type": "text",
		"tags": ["text_special", "common"],
		"tiling": -1,
		"text_type": 4,
		"layer": 20,
		"base_color": Vector2i(2, 1),
		"active_color": Vector2i(2, 2),
	},
	"text_on": {
		"unit_type": "text",
		"tags": ["text_condition", "common"],
		"tiling": -1,
		"text_type": 7,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_open": {
		"unit_type": "text",
		"tags": ["text_quality", "common", "obstacle"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(6, 1),
		"active_color": Vector2i(2, 4),
	},
	"text_you2": {
		"unit_type": "text",
		"tags": ["text_quality", "text_special", "common", "movement"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(4, 0),
		"active_color": Vector2i(4, 1),
	},
	"text_play": {
		"unit_type": "text",
		"tags": ["text_verb", "common", "music"],
		"tiling": -1,
		"text_type": 1,
		"layer": 20,
		"base_color": Vector2i(5, 1),
		"active_color": Vector2i(5, 3),
		"arg_type": [8],
		"custom_objects": ["c", "csharp", "cflat", "d", "dsharp", "dflat", "e", "esharp", "eflat", "f", "fsharp", "fflat", "g", "gsharp", "gflat", "a", "asharp", "aflat", "b", "bsharp", "bflat", "c4", "csharp4", "cflat4", "d4", "dsharp4", "dflat4", "e4", "esharp4", "eflat4", "f4", "fsharp4", "fflat4", "g4", "gsharp4", "gflat4", "a4", "asharp4", "aflat4", "b4", "bsharp4", "bflat4", "c5", "csharp5", "cflat5", "d5", "dsharp5", "dflat5", "e5", "esharp5", "eflat5", "f5", "fsharp5", "fflat5", "g5", "gsharp5", "gflat5", "a5", "asharp5", "aflat5", "b5", "bsharp5", "bflat5", "c6", "csharp6", "d6", "dsharp6", "dflat6", "e6", "esharp6", "eflat6", "f6", "fsharp6", "fflat6", "g6", "gsharp6", "gflat6", "a6", "aflat6"],
	},
	"text_powered": {
		"unit_type": "text",
		"tags": ["text_condition", "text_prefix", "machine"],
		"tiling": -1,
		"text_type": 3,
		"layer": 20,
		"base_color": Vector2i(6, 1),
		"active_color": Vector2i(2, 4),
	},
	"text_power": {
		"unit_type": "text",
		"tags": ["text_quality", "machine"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(6, 1),
		"active_color": Vector2i(2, 4),
	},
	"text_pull": {
		"unit_type": "text",
		"tags": ["text_quality", "common", "obstacle", "movement"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(6, 1),
		"active_color": Vector2i(6, 2),
	},
	"text_push": {
		"unit_type": "text",
		"tags": ["text_quality", "common", "obstacle", "movement"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(6, 0),
		"active_color": Vector2i(6, 1),
	},
	"text_sad": {
		"unit_type": "text",
		"tags": ["text_quality", "decorative"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(1, 1),
		"active_color": Vector2i(3, 2),
	},
	"text_safe": {
		"unit_type": "text",
		"tags": ["text_quality", "common"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_shift": {
		"unit_type": "text",
		"tags": ["text_quality", "common", "machine", "movement"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(1, 2),
		"active_color": Vector2i(1, 3),
	},
	"text_shut": {
		"unit_type": "text",
		"tags": ["text_quality", "common", "obstacle"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(2, 1),
		"active_color": Vector2i(2, 2),
	},
	"text_sink": {
		"unit_type": "text",
		"tags": ["text_quality", "common", "obstacle", "water", "danger"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(1, 2),
		"active_color": Vector2i(1, 3),
	},
	"text_sleep": {
		"unit_type": "text",
		"tags": ["text_quality", "sky", "common", "movement"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(1, 3),
		"active_color": Vector2i(1, 4),
	},
	"text_stop": {
		"unit_type": "text",
		"tags": ["text_quality", "common", "movement", "obstacle"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(5, 0),
		"active_color": Vector2i(5, 1),
	},
	"text_swap": {
		"unit_type": "text",
		"tags": ["text_quality", "abstract", "common", "movement"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(3, 0),
		"active_color": Vector2i(3, 1),
	},
	"text_tele": {
		"unit_type": "text",
		"tags": ["text_quality", "abstract", "machine", "movement"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(1, 2),
		"active_color": Vector2i(1, 4),
	},
	"text_text": {
		"unit_type": "text",
		"tags": ["text_special", "common", "abstract"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(4, 0),
		"active_color": Vector2i(4, 1),
	},
	"tile": {
		"unit_type": "object",
		"tags": ["common", "floor", "decorative", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 4,
		"base_color": Vector2i(0, 0),
	},
	"text_tile": {
		"unit_type": "text",
		"tags": ["common", "floor", "decorative", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(1, 1),
		"active_color": Vector2i(0, 1),
	},
	"tree": {
		"unit_type": "object",
		"tags": ["forest", "plant", "obstacle"],
		"tiling": -1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(5, 2),
	},
	"text_tree": {
		"unit_type": "text",
		"tags": ["forest", "plant", "obstacle"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(5, 1),
		"active_color": Vector2i(5, 2),
	},
	"ufo": {
		"unit_type": "object",
		"tags": ["sky", "machine"],
		"tiling": -1,
		"text_type": 0,
		"layer": 17,
		"base_color": Vector2i(4, 2),
	},
	"text_ufo": {
		"unit_type": "text",
		"tags": ["sky", "machine"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(4, 0),
		"active_color": Vector2i(4, 1),
	},
	"wall": {
		"unit_type": "object",
		"tags": ["common", "obstacle", "town"],
		"tiling": 1,
		"text_type": 0,
		"layer": 14,
		"base_color": Vector2i(1, 1),
	},
	"text_wall": {
		"unit_type": "text",
		"tags": ["common", "obstacle", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(1, 1),
		"active_color": Vector2i(0, 1),
	},
	"water": {
		"unit_type": "object",
		"tags": ["water", "obstacle", "danger"],
		"tiling": 1,
		"text_type": 0,
		"layer": 2,
		"base_color": Vector2i(1, 3),
	},
	"text_water": {
		"unit_type": "text",
		"tags": ["water", "obstacle", "danger"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(1, 2),
		"active_color": Vector2i(1, 3),
	},
	"text_weak": {
		"unit_type": "text",
		"tags": ["text_quality", "danger"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(1, 1),
		"active_color": Vector2i(1, 2),
	},
	"text_win": {
		"unit_type": "text",
		"tags": ["text_quality", "common"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(6, 1),
		"active_color": Vector2i(2, 4),
	},
	"text_without": {
		"unit_type": "text",
		"tags": ["text_condition", "common"],
		"tiling": -1,
		"text_type": 7,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_wonder": {
		"unit_type": "text",
		"tags": ["text_quality", "decorative"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_word": {
		"unit_type": "text",
		"tags": ["text_quality", "text_special"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(0, 2),
		"active_color": Vector2i(0, 3),
	},
	"text_you": {
		"unit_type": "text",
		"tags": ["text_quality", "common", "movement"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(4, 0),
		"active_color": Vector2i(4, 1),
	},
	"husks": {
		"unit_type": "object",
		"tags": ["plant", "autumn", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 9,
		"base_color": Vector2i(6, 1),
	},
	"trees": {
		"unit_type": "object",
		"tags": ["forest", "plant", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 9,
		"base_color": Vector2i(5, 2),
	},
	"text_a": {
		"unit_type": "text",
		"tags": ["text_letter", "music"],
		"tiling": -1,
		"text_type": 5,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_b": {
		"unit_type": "text",
		"tags": ["text_letter", "music"],
		"tiling": -1,
		"text_type": 5,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_c": {
		"unit_type": "text",
		"tags": ["text_letter", "music"],
		"tiling": -1,
		"text_type": 5,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_d": {
		"unit_type": "text",
		"tags": ["text_letter", "music"],
		"tiling": -1,
		"text_type": 5,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_e": {
		"unit_type": "text",
		"tags": ["text_letter", "music"],
		"tiling": -1,
		"text_type": 5,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_f": {
		"unit_type": "text",
		"tags": ["text_letter", "music"],
		"tiling": -1,
		"text_type": 5,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_g": {
		"unit_type": "text",
		"tags": ["text_letter", "music"],
		"tiling": -1,
		"text_type": 5,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_h": {
		"unit_type": "text",
		"tags": ["text_letter"],
		"tiling": -1,
		"text_type": 5,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_i": {
		"unit_type": "text",
		"tags": ["text_letter"],
		"tiling": -1,
		"text_type": 5,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_l": {
		"unit_type": "text",
		"tags": ["text_letter"],
		"tiling": -1,
		"text_type": 5,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_m": {
		"unit_type": "text",
		"tags": ["text_letter"],
		"tiling": -1,
		"text_type": 5,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_n": {
		"unit_type": "text",
		"tags": ["text_letter"],
		"tiling": -1,
		"text_type": 5,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_o": {
		"unit_type": "text",
		"tags": ["text_letter"],
		"tiling": -1,
		"text_type": 5,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_r": {
		"unit_type": "text",
		"tags": ["text_letter"],
		"tiling": -1,
		"text_type": 5,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_s": {
		"unit_type": "text",
		"tags": ["text_letter"],
		"tiling": -1,
		"text_type": 5,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_t": {
		"unit_type": "text",
		"tags": ["text_letter"],
		"tiling": -1,
		"text_type": 5,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_u": {
		"unit_type": "text",
		"tags": ["text_letter"],
		"tiling": -1,
		"text_type": 5,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_v": {
		"unit_type": "text",
		"tags": ["text_letter"],
		"tiling": -1,
		"text_type": 5,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_j": {
		"unit_type": "text",
		"tags": ["text_letter"],
		"tiling": -1,
		"text_type": 5,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_k": {
		"unit_type": "text",
		"tags": ["text_letter"],
		"tiling": -1,
		"text_type": 5,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_p": {
		"unit_type": "text",
		"tags": ["text_letter"],
		"tiling": -1,
		"text_type": 5,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_q": {
		"unit_type": "text",
		"tags": ["text_letter"],
		"tiling": -1,
		"text_type": 5,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_y": {
		"unit_type": "text",
		"tags": ["text_letter"],
		"tiling": -1,
		"text_type": 5,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_z": {
		"unit_type": "text",
		"tags": ["text_letter"],
		"tiling": -1,
		"text_type": 5,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_broken": {
		"unit_type": "text",
		"tags": ["text_quality", "abstract"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(4, 0),
		"active_color": Vector2i(4, 1),
	},
	"text_nudgeright": {
		"unit_type": "text",
		"tags": ["text_quality", "common", "movement"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(5, 1),
		"active_color": Vector2i(5, 3),
	},
	"text_nudgeup": {
		"unit_type": "text",
		"tags": ["text_quality", "common", "movement"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(5, 1),
		"active_color": Vector2i(5, 3),
	},
	"text_nudgeleft": {
		"unit_type": "text",
		"tags": ["text_quality", "common", "movement"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(5, 1),
		"active_color": Vector2i(5, 3),
	},
	"text_nudgedown": {
		"unit_type": "text",
		"tags": ["text_quality", "common", "movement"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(5, 1),
		"active_color": Vector2i(5, 3),
	},
	"text_turn": {
		"unit_type": "text",
		"tags": ["text_quality", "common", "movement"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(1, 2),
		"active_color": Vector2i(1, 4),
	},
	"text_deturn": {
		"unit_type": "text",
		"tags": ["text_quality", "common", "movement"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(1, 2),
		"active_color": Vector2i(1, 4),
	},
	"text_done": {
		"unit_type": "text",
		"tags": ["text_quality", "text_special"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_mimic": {
		"unit_type": "text",
		"tags": ["text_verb", "abstract"],
		"tiling": -1,
		"text_type": 1,
		"layer": 20,
		"base_color": Vector2i(2, 1),
		"active_color": Vector2i(2, 2),
	},
	"sign": {
		"unit_type": "object",
		"tags": ["common", "item", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(6, 1),
	},
	"text_sign": {
		"unit_type": "text",
		"tags": ["common", "item", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(6, 1),
		"active_color": Vector2i(6, 2),
	},
	"text_still": {
		"unit_type": "text",
		"tags": ["text_quality", "abstract", "movement"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(2, 1),
		"active_color": Vector2i(2, 2),
	},
	"circle": {
		"unit_type": "object",
		"tags": ["item", "abstract"],
		"tiling": -1,
		"text_type": 0,
		"layer": 17,
		"base_color": Vector2i(5, 3),
	},
	"text_circle": {
		"unit_type": "text",
		"tags": ["item", "abstract"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(5, 1),
		"active_color": Vector2i(5, 3),
	},
	"square": {
		"unit_type": "object",
		"tags": ["item", "abstract"],
		"tiling": -1,
		"text_type": 0,
		"layer": 17,
		"base_color": Vector2i(4, 1),
	},
	"text_square": {
		"unit_type": "text",
		"tags": ["item", "abstract"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(4, 0),
		"active_color": Vector2i(4, 1),
	},
	"triangle": {
		"unit_type": "object",
		"tags": ["item", "abstract"],
		"tiling": -1,
		"text_type": 0,
		"layer": 17,
		"base_color": Vector2i(3, 2),
	},
	"text_triangle": {
		"unit_type": "text",
		"tags": ["item", "abstract"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(3, 2),
		"active_color": Vector2i(3, 3),
	},
	"crystal": {
		"unit_type": "object",
		"tags": ["cave", "obstacle", "item"],
		"tiling": 0,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(4, 2),
	},
	"text_crystal": {
		"unit_type": "text",
		"tags": ["cave", "obstacle", "item"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(4, 1),
		"active_color": Vector2i(4, 2),
	},
	"foot": {
		"unit_type": "object",
		"tags": ["abstract"],
		"tiling": 0,
		"text_type": 0,
		"layer": 17,
		"base_color": Vector2i(3, 1),
	},
	"text_foot": {
		"unit_type": "text",
		"tags": ["abstract"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(3, 1),
		"active_color": Vector2i(4, 2),
	},
	"eye": {
		"unit_type": "object",
		"tags": ["abstract"],
		"tiling": 2,
		"text_type": 0,
		"layer": 19,
		"base_color": Vector2i(3, 1),
	},
	"text_eye": {
		"unit_type": "text",
		"tags": ["abstract"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(3, 1),
		"active_color": Vector2i(4, 2),
	},
	"worm": {
		"unit_type": "object",
		"tags": ["forest", "animal"],
		"tiling": 2,
		"text_type": 0,
		"layer": 19,
		"base_color": Vector2i(0, 3),
	},
	"text_worm": {
		"unit_type": "text",
		"tags": ["forest", "animal"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_above": {
		"unit_type": "text",
		"tags": ["text_condition", "common"],
		"tiling": -1,
		"text_type": 7,
		"layer": 20,
		"base_color": Vector2i(1, 2),
		"active_color": Vector2i(1, 4),
	},
	"text_below": {
		"unit_type": "text",
		"tags": ["text_condition", "common"],
		"tiling": -1,
		"text_type": 7,
		"layer": 20,
		"base_color": Vector2i(1, 2),
		"active_color": Vector2i(1, 4),
	},
	"text_select": {
		"unit_type": "text",
		"tags": ["text_quality", "text_special", "common"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(2, 3),
		"active_color": Vector2i(2, 4),
	},
	"gem": {
		"unit_type": "object",
		"tags": ["item", "cave", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(4, 2),
	},
	"text_gem": {
		"unit_type": "text",
		"tags": ["item", "cave", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(4, 1),
		"active_color": Vector2i(4, 2),
	},
	"text_husks": {
		"unit_type": "text",
		"tags": ["plant", "autumn", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(6, 1),
		"active_color": Vector2i(6, 2),
	},
	"text_trees": {
		"unit_type": "text",
		"tags": ["forest", "plant", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(5, 1),
		"active_color": Vector2i(5, 2),
	},
	"text_feeling": {
		"unit_type": "text",
		"tags": ["text_condition"],
		"tiling": -1,
		"text_type": 7,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
		"arg_type": [2],
	},
	"text_cyan": {
		"unit_type": "text",
		"tags": ["text_quality", "decorative", "colour"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(1, 2),
		"active_color": Vector2i(1, 4),
	},
	"track": {
		"unit_type": "object",
		"tags": ["machine", "floor", "town"],
		"tiling": 1,
		"text_type": 0,
		"layer": 9,
		"base_color": Vector2i(6, 0),
	},
	"text_track": {
		"unit_type": "text",
		"tags": ["machine", "floor", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(6, 0),
		"active_color": Vector2i(6, 1),
	},
	"train": {
		"unit_type": "object",
		"tags": ["machine", "item", "danger", "town"],
		"tiling": 0,
		"text_type": 0,
		"layer": 18,
		"base_color": Vector2i(5, 2),
	},
	"text_train": {
		"unit_type": "text",
		"tags": ["machine", "item", "danger", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(5, 1),
		"active_color": Vector2i(5, 2),
	},
	"text_rosy": {
		"unit_type": "text",
		"tags": ["text_quality", "decorative", "colour"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(4, 1),
		"active_color": Vector2i(4, 2),
	},
	"text_lime": {
		"unit_type": "text",
		"tags": ["text_quality", "decorative", "colour"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(5, 1),
		"active_color": Vector2i(5, 3),
	},
	"text_silver": {
		"unit_type": "text",
		"tags": ["text_quality", "decorative", "colour"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 2),
	},
	"ring": {
		"unit_type": "object",
		"tags": ["item", "decorative", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 17,
		"base_color": Vector2i(2, 4),
	},
	"text_ring": {
		"unit_type": "text",
		"tags": ["item", "decorative", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(2, 3),
		"active_color": Vector2i(2, 4),
	},
	"arrow": {
		"unit_type": "object",
		"tags": ["abstract", "movement"],
		"tiling": 0,
		"text_type": 0,
		"layer": 9,
		"base_color": Vector2i(5, 2),
	},
	"text_arrow": {
		"unit_type": "text",
		"tags": ["abstract", "movement"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(5, 1),
		"active_color": Vector2i(5, 2),
	},
	"cart": {
		"unit_type": "object",
		"tags": ["machine", "item", "danger", "town"],
		"tiling": 0,
		"text_type": 0,
		"layer": 18,
		"base_color": Vector2i(5, 2),
	},
	"text_cart": {
		"unit_type": "text",
		"tags": ["machine", "item", "danger", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(5, 1),
		"active_color": Vector2i(5, 2),
	},
	"book": {
		"unit_type": "object",
		"tags": ["item", "ruins", "decorative", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(2, 3),
	},
	"text_book": {
		"unit_type": "text",
		"tags": ["item", "ruins", "decorative", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(6, 1),
		"active_color": Vector2i(2, 3),
	},
	"tower": {
		"unit_type": "object",
		"tags": ["ruins", "obstacle", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 17,
		"base_color": Vector2i(0, 1),
	},
	"text_tower": {
		"unit_type": "text",
		"tags": ["ruins", "obstacle", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(1, 1),
		"active_color": Vector2i(0, 1),
	},
	"seed": {
		"unit_type": "object",
		"tags": ["forest", "plant", "item"],
		"tiling": -1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(6, 2),
	},
	"text_seed": {
		"unit_type": "text",
		"tags": ["forest", "plant", "item"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(6, 1),
		"active_color": Vector2i(6, 2),
	},
	"sprout": {
		"unit_type": "object",
		"tags": ["forest", "plant", "item"],
		"tiling": -1,
		"text_type": 0,
		"layer": 17,
		"base_color": Vector2i(5, 3),
	},
	"text_sprout": {
		"unit_type": "text",
		"tags": ["forest", "plant", "item"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(5, 1),
		"active_color": Vector2i(5, 3),
	},
	"jiji": {
		"unit_type": "object",
		"tags": ["animal", "common"],
		"tiling": 2,
		"text_type": 0,
		"layer": 18,
		"base_color": Vector2i(2, 3),
	},
	"text_jiji": {
		"unit_type": "text",
		"tags": ["animal", "common"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(2, 2),
		"active_color": Vector2i(2, 3),
	},
	"fofo": {
		"unit_type": "object",
		"tags": ["animal", "common"],
		"tiling": 2,
		"text_type": 0,
		"layer": 18,
		"base_color": Vector2i(5, 2),
	},
	"text_fofo": {
		"unit_type": "text",
		"tags": ["animal", "common"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(5, 1),
		"active_color": Vector2i(5, 2),
	},
	"vine": {
		"unit_type": "object",
		"tags": ["obstacle", "decorative", "forest", "plant"],
		"tiling": 1,
		"text_type": 0,
		"layer": 15,
		"base_color": Vector2i(5, 2),
	},
	"text_vine": {
		"unit_type": "text",
		"tags": ["obstacle", "decorative", "forest", "plant"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(5, 1),
		"active_color": Vector2i(5, 2),
	},
	"wind": {
		"unit_type": "object",
		"tags": ["abstract", "movement", "mountain", "sky"],
		"tiling": 0,
		"text_type": 0,
		"layer": 8,
		"base_color": Vector2i(1, 4),
	},
	"text_wind": {
		"unit_type": "text",
		"tags": ["abstract", "movement", "mountain", "sky"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(1, 3),
		"active_color": Vector2i(1, 4),
	},
	"fort": {
		"unit_type": "object",
		"tags": ["obstacle", "ruins", "town"],
		"tiling": 1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(1, 1),
	},
	"text_fort": {
		"unit_type": "text",
		"tags": ["obstacle", "ruins", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(1, 1),
		"active_color": Vector2i(0, 1),
	},
	"text_auto": {
		"unit_type": "text",
		"tags": ["text_quality", "movement", "text_special"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(4, 0),
		"active_color": Vector2i(4, 1),
	},
	"bee": {
		"unit_type": "object",
		"tags": ["animal", "forest"],
		"tiling": 0,
		"text_type": 0,
		"layer": 17,
		"base_color": Vector2i(2, 4),
	},
	"text_bee": {
		"unit_type": "text",
		"tags": ["animal", "forest"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(6, 1),
		"active_color": Vector2i(2, 4),
	},
	"pants": {
		"unit_type": "object",
		"tags": ["item", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(3, 2),
	},
	"text_pants": {
		"unit_type": "text",
		"tags": ["item", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(3, 2),
		"active_color": Vector2i(3, 3),
	},
	"text_0": {
		"unit_type": "text",
		"tags": ["text_letter"],
		"tiling": -1,
		"text_type": 5,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_1": {
		"unit_type": "text",
		"tags": ["text_letter"],
		"tiling": -1,
		"text_type": 5,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_2": {
		"unit_type": "text",
		"tags": ["text_letter"],
		"tiling": -1,
		"text_type": 5,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_3": {
		"unit_type": "text",
		"tags": ["text_letter", "music"],
		"tiling": -1,
		"text_type": 5,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_4": {
		"unit_type": "text",
		"tags": ["text_letter", "music"],
		"tiling": -1,
		"text_type": 5,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_5": {
		"unit_type": "text",
		"tags": ["text_letter", "music"],
		"tiling": -1,
		"text_type": 5,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_6": {
		"unit_type": "text",
		"tags": ["text_letter", "music"],
		"tiling": -1,
		"text_type": 5,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_7": {
		"unit_type": "text",
		"tags": ["text_letter"],
		"tiling": -1,
		"text_type": 5,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_8": {
		"unit_type": "text",
		"tags": ["text_letter"],
		"tiling": -1,
		"text_type": 5,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_9": {
		"unit_type": "text",
		"tags": ["text_letter"],
		"tiling": -1,
		"text_type": 5,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_sharp": {
		"unit_type": "text",
		"tags": ["text_letter", "music"],
		"tiling": -1,
		"text_type": 5,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_flat": {
		"unit_type": "text",
		"tags": ["text_letter", "music"],
		"tiling": -1,
		"text_type": 5,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_revert": {
		"unit_type": "text",
		"tags": ["text_quality", "text_special"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(2, 2),
		"active_color": Vector2i(2, 3),
	},
	"lizard": {
		"unit_type": "object",
		"tags": ["animal", "forest", "cave"],
		"tiling": 2,
		"text_type": 0,
		"layer": 19,
		"base_color": Vector2i(2, 2),
	},
	"text_lizard": {
		"unit_type": "text",
		"tags": ["animal", "forest", "cave"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(2, 1),
		"active_color": Vector2i(2, 2),
	},
	"shell": {
		"unit_type": "object",
		"tags": ["animal", "water", "item"],
		"tiling": -1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(4, 2),
	},
	"text_shell": {
		"unit_type": "text",
		"tags": ["animal", "water", "item"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(4, 1),
		"active_color": Vector2i(4, 2),
	},
	"fish": {
		"unit_type": "object",
		"tags": ["animal", "water", "movement"],
		"tiling": 0,
		"text_type": 0,
		"layer": 17,
		"base_color": Vector2i(1, 3),
	},
	"text_fish": {
		"unit_type": "text",
		"tags": ["animal", "water", "movement"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(1, 2),
		"active_color": Vector2i(1, 3),
	},
	"house": {
		"unit_type": "object",
		"tags": ["obstacle", "decorative", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(6, 1),
	},
	"text_house": {
		"unit_type": "text",
		"tags": ["obstacle", "decorative", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(6, 1),
		"active_color": Vector2i(6, 2),
	},
	"gate": {
		"unit_type": "object",
		"tags": ["obstacle", "decorative", "ruins"],
		"tiling": -1,
		"text_type": 0,
		"layer": 15,
		"base_color": Vector2i(2, 2),
	},
	"text_gate": {
		"unit_type": "text",
		"tags": ["obstacle", "decorative", "ruins"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(2, 1),
		"active_color": Vector2i(2, 2),
	},
	"boat": {
		"unit_type": "object",
		"tags": ["water", "movement", "machine", "decorative"],
		"tiling": 0,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(6, 1),
	},
	"text_boat": {
		"unit_type": "text",
		"tags": ["water", "movement", "machine", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(6, 1),
		"active_color": Vector2i(6, 2),
	},
	"pumpkin": {
		"unit_type": "object",
		"tags": ["plant", "autumn", "decorative"],
		"tiling": 0,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(2, 3),
	},
	"text_pumpkin": {
		"unit_type": "text",
		"tags": ["plant", "autumn", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(6, 1),
		"active_color": Vector2i(2, 3),
	},
	"lamp": {
		"unit_type": "object",
		"tags": ["item", "autumn", "decorative", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(2, 4),
	},
	"text_lamp": {
		"unit_type": "text",
		"tags": ["item", "autumn", "decorative", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(6, 2),
		"active_color": Vector2i(2, 4),
	},
	"lift": {
		"unit_type": "object",
		"tags": ["machine", "movement", "town"],
		"tiling": 0,
		"text_type": 0,
		"layer": 17,
		"base_color": Vector2i(0, 1),
	},
	"text_lift": {
		"unit_type": "text",
		"tags": ["machine", "movement", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 2),
	},
	"ear": {
		"unit_type": "object",
		"tags": ["abstract"],
		"tiling": 0,
		"text_type": 0,
		"layer": 18,
		"base_color": Vector2i(3, 1),
	},
	"text_ear": {
		"unit_type": "text",
		"tags": ["abstract"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(3, 1),
		"active_color": Vector2i(4, 2),
	},
	"nose": {
		"unit_type": "object",
		"tags": ["abstract"],
		"tiling": 0,
		"text_type": 0,
		"layer": 18,
		"base_color": Vector2i(3, 1),
	},
	"text_nose": {
		"unit_type": "text",
		"tags": ["abstract"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(3, 1),
		"active_color": Vector2i(4, 2),
	},
	"monitor": {
		"unit_type": "object",
		"tags": ["machine", "item", "decorative", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(0, 1),
	},
	"text_monitor": {
		"unit_type": "text",
		"tags": ["machine", "item", "decorative", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 2),
	},
	"stick": {
		"unit_type": "object",
		"tags": ["item", "decorative", "forest"],
		"tiling": -1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(6, 1),
	},
	"text_stick": {
		"unit_type": "text",
		"tags": ["item", "decorative", "forest"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(6, 1),
		"active_color": Vector2i(6, 2),
	},
	"bucket": {
		"unit_type": "object",
		"tags": ["item", "decorative", "cave"],
		"tiling": -1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(2, 2),
	},
	"text_bucket": {
		"unit_type": "text",
		"tags": ["item", "decorative", "cave"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(2, 1),
		"active_color": Vector2i(2, 2),
	},
	"shovel": {
		"unit_type": "object",
		"tags": ["item", "decorative", "cave"],
		"tiling": 0,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(3, 1),
	},
	"text_shovel": {
		"unit_type": "text",
		"tags": ["item", "decorative", "cave"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(3, 1),
		"active_color": Vector2i(4, 2),
	},
	"it": {
		"unit_type": "object",
		"tags": ["common", "animal"],
		"tiling": 2,
		"text_type": 0,
		"layer": 18,
		"base_color": Vector2i(1, 4),
	},
	"text_it": {
		"unit_type": "text",
		"tags": ["common", "animal"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(1, 2),
		"active_color": Vector2i(1, 4),
	},
	"plane": {
		"unit_type": "object",
		"tags": ["sky", "movement", "machine"],
		"tiling": 0,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(2, 2),
	},
	"text_plane": {
		"unit_type": "text",
		"tags": ["sky", "movement", "machine"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(2, 1),
		"active_color": Vector2i(2, 2),
	},
	"text_lockeddown": {
		"unit_type": "text",
		"tags": ["text_quality", "abstract", "movement"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(4, 1),
		"active_color": Vector2i(4, 2),
	},
	"text_lockedright": {
		"unit_type": "text",
		"tags": ["text_quality", "abstract", "movement"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(4, 1),
		"active_color": Vector2i(4, 2),
	},
	"text_lockedup": {
		"unit_type": "text",
		"tags": ["text_quality", "abstract", "movement"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(4, 1),
		"active_color": Vector2i(4, 2),
	},
	"text_lockedleft": {
		"unit_type": "text",
		"tags": ["text_quality", "abstract", "movement"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(4, 1),
		"active_color": Vector2i(4, 2),
	},
	"text_phantom": {
		"unit_type": "text",
		"tags": ["text_quality", "abstract", "movement", "obstacle"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(1, 1),
		"active_color": Vector2i(0, 1),
	},
	"planet": {
		"unit_type": "object",
		"tags": ["sky", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(2, 3),
	},
	"text_planet": {
		"unit_type": "text",
		"tags": ["sky", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(2, 2),
		"active_color": Vector2i(2, 3),
	},
	"road": {
		"unit_type": "object",
		"tags": ["floor", "decorative", "town"],
		"tiling": 1,
		"text_type": 0,
		"layer": 7,
		"base_color": Vector2i(0, 1),
	},
	"text_road": {
		"unit_type": "text",
		"tags": ["floor", "decorative", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 2),
	},
	"banana": {
		"unit_type": "object",
		"tags": ["plant", "forest", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(2, 4),
	},
	"text_banana": {
		"unit_type": "text",
		"tags": ["plant", "forest", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(6, 2),
		"active_color": Vector2i(2, 4),
	},
	"burger": {
		"unit_type": "object",
		"tags": ["town", "item", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(2, 3),
	},
	"text_burger": {
		"unit_type": "text",
		"tags": ["town", "item", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(6, 1),
		"active_color": Vector2i(2, 3),
	},
	"drink": {
		"unit_type": "object",
		"tags": ["town", "item", "decorative", "water"],
		"tiling": -1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(4, 4),
	},
	"text_drink": {
		"unit_type": "text",
		"tags": ["town", "item", "decorative", "water"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(3, 2),
		"active_color": Vector2i(4, 4),
	},
	"turnip": {
		"unit_type": "object",
		"tags": ["plant", "forest", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(6, 2),
	},
	"text_turnip": {
		"unit_type": "text",
		"tags": ["plant", "forest", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(6, 1),
		"active_color": Vector2i(6, 2),
	},
	"pixel": {
		"unit_type": "object",
		"tags": ["obstacle", "abstract"],
		"tiling": -1,
		"text_type": 0,
		"layer": 9,
		"base_color": Vector2i(0, 3),
	},
	"text_pixel": {
		"unit_type": "text",
		"tags": ["obstacle", "abstract"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"guitar": {
		"unit_type": "object",
		"tags": ["item", "decorative", "music"],
		"tiling": -1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(6, 2),
	},
	"text_guitar": {
		"unit_type": "text",
		"tags": ["item", "decorative", "music"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(6, 1),
		"active_color": Vector2i(6, 2),
	},
	"piano": {
		"unit_type": "object",
		"tags": ["item", "decorative", "music"],
		"tiling": 0,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(1, 3),
	},
	"text_piano": {
		"unit_type": "text",
		"tags": ["item", "decorative", "music"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(1, 2),
		"active_color": Vector2i(1, 3),
	},
	"sax": {
		"unit_type": "object",
		"tags": ["item", "decorative", "music"],
		"tiling": 0,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(3, 4),
	},
	"text_sax": {
		"unit_type": "text",
		"tags": ["item", "decorative", "music"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(6, 1),
		"active_color": Vector2i(3, 4),
	},
	"blob": {
		"unit_type": "object",
		"tags": ["obstacle", "danger"],
		"tiling": 1,
		"text_type": 0,
		"layer": 8,
		"base_color": Vector2i(5, 2),
	},
	"text_blob": {
		"unit_type": "text",
		"tags": ["obstacle", "danger"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(5, 1),
		"active_color": Vector2i(5, 2),
	},
	"drum": {
		"unit_type": "object",
		"tags": ["item", "decorative", "music"],
		"tiling": -1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(2, 3),
	},
	"text_drum": {
		"unit_type": "text",
		"tags": ["item", "decorative", "music"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(2, 2),
		"active_color": Vector2i(2, 3),
	},
	"hihat": {
		"unit_type": "object",
		"tags": ["item", "decorative", "music"],
		"tiling": -1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(2, 4),
	},
	"text_hihat": {
		"unit_type": "text",
		"tags": ["item", "decorative", "music"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(6, 1),
		"active_color": Vector2i(2, 4),
	},
	"text_group2": {
		"unit_type": "text",
		"tags": ["common", "text_special"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(2, 1),
		"active_color": Vector2i(2, 2),
	},
	"text_group3": {
		"unit_type": "text",
		"tags": ["common", "text_special"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(5, 2),
		"active_color": Vector2i(5, 3),
	},
	"text_party": {
		"unit_type": "text",
		"tags": ["text_quality", "decorative"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(2, 2),
		"active_color": Vector2i(2, 3),
	},
	"potato": {
		"unit_type": "object",
		"tags": ["plant", "forest", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(6, 1),
	},
	"text_potato": {
		"unit_type": "text",
		"tags": ["plant", "forest", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(6, 1),
		"active_color": Vector2i(6, 2),
	},
	"text_pet": {
		"unit_type": "text",
		"tags": ["text_quality", "decorative"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(3, 1),
		"active_color": Vector2i(4, 2),
	},
	"donut": {
		"unit_type": "object",
		"tags": ["item", "decorative", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(4, 1),
	},
	"text_donut": {
		"unit_type": "text",
		"tags": ["item", "decorative", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(4, 1),
		"active_color": Vector2i(4, 2),
	},
	"text_reverse": {
		"unit_type": "text",
		"tags": ["text_quality", "common", "movement"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(5, 2),
		"active_color": Vector2i(5, 3),
	},
	"text_besideleft": {
		"unit_type": "text",
		"tags": ["text_condition", "common"],
		"tiling": -1,
		"text_type": 7,
		"layer": 20,
		"base_color": Vector2i(1, 2),
		"active_color": Vector2i(1, 4),
	},
	"text_besideright": {
		"unit_type": "text",
		"tags": ["text_condition", "common"],
		"tiling": -1,
		"text_type": 7,
		"layer": 20,
		"base_color": Vector2i(1, 2),
		"active_color": Vector2i(1, 4),
	},
	"frog": {
		"unit_type": "object",
		"tags": ["water", "animal"],
		"tiling": 2,
		"text_type": 0,
		"layer": 18,
		"base_color": Vector2i(5, 3),
	},
	"text_frog": {
		"unit_type": "text",
		"tags": ["water", "animal"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(5, 1),
		"active_color": Vector2i(5, 3),
	},
	"trumpet": {
		"unit_type": "object",
		"tags": ["item", "decorative", "music"],
		"tiling": 0,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(3, 4),
	},
	"text_trumpet": {
		"unit_type": "text",
		"tags": ["item", "decorative", "music"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(2, 3),
		"active_color": Vector2i(2, 4),
	},
	"pawn": {
		"unit_type": "object",
		"tags": ["item", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 17,
		"base_color": Vector2i(2, 2),
	},
	"text_pawn": {
		"unit_type": "text",
		"tags": ["item", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(2, 1),
		"active_color": Vector2i(2, 2),
	},
	"knight": {
		"unit_type": "object",
		"tags": ["item", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 17,
		"base_color": Vector2i(2, 2),
	},
	"text_knight": {
		"unit_type": "text",
		"tags": ["item", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(2, 1),
		"active_color": Vector2i(2, 2),
	},
	"turtle": {
		"unit_type": "object",
		"tags": ["water", "animal", "forest"],
		"tiling": 2,
		"text_type": 0,
		"layer": 18,
		"base_color": Vector2i(5, 4),
	},
	"text_turtle": {
		"unit_type": "text",
		"tags": ["water", "animal", "forest"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(5, 2),
		"active_color": Vector2i(5, 4),
	},
	"cat": {
		"unit_type": "object",
		"tags": ["animal", "forest", "town"],
		"tiling": 2,
		"text_type": 0,
		"layer": 18,
		"base_color": Vector2i(6, 2),
	},
	"text_cat": {
		"unit_type": "text",
		"tags": ["animal", "forest", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(6, 1),
		"active_color": Vector2i(6, 2),
	},
	"sword": {
		"unit_type": "object",
		"tags": ["item", "decorative", "danger"],
		"tiling": 0,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(1, 4),
	},
	"text_sword": {
		"unit_type": "text",
		"tags": ["item", "decorative", "danger"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(1, 2),
		"active_color": Vector2i(1, 4),
	},
	"clock": {
		"unit_type": "object",
		"tags": ["item", "decorative", "town"],
		"tiling": 4,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(1, 3),
	},
	"text_clock": {
		"unit_type": "text",
		"tags": ["item", "decorative", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(1, 2),
		"active_color": Vector2i(1, 3),
	},
	"bed": {
		"unit_type": "object",
		"tags": ["item", "decorative", "town"],
		"tiling": 0,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(0, 3),
	},
	"text_bed": {
		"unit_type": "text",
		"tags": ["item", "decorative", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"pizza": {
		"unit_type": "object",
		"tags": ["item", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(2, 3),
	},
	"text_pizza": {
		"unit_type": "text",
		"tags": ["item", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(2, 2),
		"active_color": Vector2i(2, 3),
	},
	"vase": {
		"unit_type": "object",
		"tags": ["item", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(0, 2),
	},
	"text_vase": {
		"unit_type": "text",
		"tags": ["item", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 1),
	},
	"bottle": {
		"unit_type": "object",
		"tags": ["item", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(1, 4),
	},
	"text_bottle": {
		"unit_type": "text",
		"tags": ["item", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(1, 2),
		"active_color": Vector2i(1, 4),
	},
	"car": {
		"unit_type": "object",
		"tags": ["machine", "danger", "town"],
		"tiling": 0,
		"text_type": 0,
		"layer": 17,
		"base_color": Vector2i(2, 2),
	},
	"text_car": {
		"unit_type": "text",
		"tags": ["machine", "danger", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(2, 1),
		"active_color": Vector2i(2, 2),
	},
	"egg": {
		"unit_type": "object",
		"tags": ["item", "decorative", "animal", "forest"],
		"tiling": 0,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(0, 3),
	},
	"text_egg": {
		"unit_type": "text",
		"tags": ["item", "decorative", "animal", "forest"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"plank": {
		"unit_type": "object",
		"tags": ["floor", "town"],
		"tiling": 1,
		"text_type": 0,
		"layer": 8,
		"base_color": Vector2i(6, 0),
	},
	"text_plank": {
		"unit_type": "text",
		"tags": ["floor", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(6, 1),
		"active_color": Vector2i(6, 2),
	},
	"dog": {
		"unit_type": "object",
		"tags": ["animal", "forest", "town"],
		"tiling": 2,
		"text_type": 0,
		"layer": 18,
		"base_color": Vector2i(0, 2),
	},
	"text_dog": {
		"unit_type": "text",
		"tags": ["animal", "forest", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 2),
	},
	"mirror": {
		"unit_type": "object",
		"tags": ["item", "decorative", "town", "ruins"],
		"tiling": -1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(1, 4),
	},
	"text_mirror": {
		"unit_type": "text",
		"tags": ["item", "decorative", "town", "ruins"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(1, 3),
		"active_color": Vector2i(1, 4),
	},
	"lily": {
		"unit_type": "object",
		"tags": ["water", "decorative", "plant"],
		"tiling": -1,
		"text_type": 0,
		"layer": 9,
		"base_color": Vector2i(5, 2),
	},
	"text_lily": {
		"unit_type": "text",
		"tags": ["water", "decorative", "plant"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(5, 1),
		"active_color": Vector2i(5, 2),
	},
	"text_3d": {
		"unit_type": "text",
		"tags": ["abstract", "text_special", "text_quality"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(4, 0),
		"active_color": Vector2i(4, 1),
	},
	"lock": {
		"unit_type": "object",
		"tags": ["common", "obstacle", "item"],
		"tiling": -1,
		"text_type": 0,
		"layer": 14,
		"base_color": Vector2i(0, 2),
	},
	"text_lock": {
		"unit_type": "text",
		"tags": ["common", "obstacle", "item"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 2),
	},
	"boba": {
		"unit_type": "object",
		"tags": ["decorative", "town", "item"],
		"tiling": -1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(6, 2),
	},
	"text_boba": {
		"unit_type": "text",
		"tags": ["decorative", "town", "item"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(6, 1),
		"active_color": Vector2i(6, 2),
	},
	"badbad": {
		"unit_type": "object",
		"tags": ["animal", "common"],
		"tiling": 2,
		"text_type": 0,
		"layer": 18,
		"base_color": Vector2i(1, 4),
	},
	"text_badbad": {
		"unit_type": "text",
		"tags": ["animal", "common"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(1, 3),
		"active_color": Vector2i(1, 4),
	},
	"what": {
		"unit_type": "object",
		"tags": ["decorative", "abstract"],
		"tiling": -1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(0, 3),
	},
	"text_what": {
		"unit_type": "text",
		"tags": ["decorative", "abstract"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"text_boom": {
		"unit_type": "text",
		"tags": ["text_quality", "danger"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(2, 1),
		"active_color": Vector2i(2, 2),
	},
	"text_nextto": {
		"unit_type": "text",
		"tags": ["text_condition", "common"],
		"tiling": -1,
		"text_type": 7,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"monster": {
		"unit_type": "object",
		"tags": ["ruins", "danger", "animal"],
		"tiling": 2,
		"text_type": 0,
		"layer": 19,
		"base_color": Vector2i(4, 1),
	},
	"text_monster": {
		"unit_type": "text",
		"tags": ["ruins", "danger", "animal"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(4, 0),
		"active_color": Vector2i(4, 1),
	},
	"text_seeing": {
		"unit_type": "text",
		"tags": ["text_condition", "common"],
		"tiling": -1,
		"text_type": 7,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"teeth": {
		"unit_type": "object",
		"tags": ["abstract", "decorative"],
		"tiling": 4,
		"text_type": 0,
		"layer": 18,
		"base_color": Vector2i(0, 3),
	},
	"text_teeth": {
		"unit_type": "text",
		"tags": ["abstract", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(0, 2),
		"active_color": Vector2i(0, 3),
	},
	"lever": {
		"unit_type": "object",
		"tags": ["machine", "decorative"],
		"tiling": 0,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(0, 2),
	},
	"text_lever": {
		"unit_type": "text",
		"tags": ["machine", "decorative"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 2),
	},
	"text_write": {
		"unit_type": "text",
		"tags": ["text_verb", "text_special"],
		"tiling": -1,
		"text_type": 1,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
		"arg_type": [0, 2],
	},
	"text_powered2": {
		"unit_type": "text",
		"tags": ["text_condition", "text_prefix", "machine"],
		"tiling": -1,
		"text_type": 3,
		"layer": 20,
		"base_color": Vector2i(5, 2),
		"active_color": Vector2i(5, 3),
	},
	"text_power2": {
		"unit_type": "text",
		"tags": ["text_quality", "machine"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(5, 2),
		"active_color": Vector2i(5, 3),
	},
	"text_powered3": {
		"unit_type": "text",
		"tags": ["text_condition", "text_prefix", "machine"],
		"tiling": -1,
		"text_type": 3,
		"layer": 20,
		"base_color": Vector2i(3, 2),
		"active_color": Vector2i(4, 4),
	},
	"text_power3": {
		"unit_type": "text",
		"tags": ["text_quality", "machine"],
		"tiling": -1,
		"text_type": 2,
		"layer": 20,
		"base_color": Vector2i(3, 2),
		"active_color": Vector2i(4, 4),
	},
	"chair": {
		"unit_type": "object",
		"tags": ["town", "decorative", "item"],
		"tiling": 0,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(6, 2),
	},
	"text_chair": {
		"unit_type": "text",
		"tags": ["town", "decorative", "item"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(6, 1),
		"active_color": Vector2i(6, 2),
	},
	"table": {
		"unit_type": "object",
		"tags": ["town", "decorative", "item"],
		"tiling": -1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(6, 1),
	},
	"text_table": {
		"unit_type": "text",
		"tags": ["town", "decorative", "item"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(6, 1),
		"active_color": Vector2i(6, 2),
	},
	"cheese": {
		"unit_type": "object",
		"tags": ["town", "decorative", "item"],
		"tiling": -1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(2, 4),
	},
	"text_cheese": {
		"unit_type": "text",
		"tags": ["town", "decorative", "item"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(2, 3),
		"active_color": Vector2i(2, 4),
	},
	"bomb": {
		"unit_type": "object",
		"tags": ["machine", "danger", "item"],
		"tiling": -1,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(0, 1),
	},
	"text_bomb": {
		"unit_type": "text",
		"tags": ["machine", "danger", "item"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 2),
	},
	"paper": {
		"unit_type": "object",
		"tags": ["item", "decorative", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 9,
		"base_color": Vector2i(0, 3),
	},
	"text_paper": {
		"unit_type": "text",
		"tags": ["item", "decorative", "town"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"scissors": {
		"unit_type": "object",
		"tags": ["item", "decorative", "town", "danger"],
		"tiling": 3,
		"text_type": 0,
		"layer": 16,
		"base_color": Vector2i(1, 4),
	},
	"text_scissors": {
		"unit_type": "text",
		"tags": ["item", "decorative", "town", "danger"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(1, 2),
		"active_color": Vector2i(1, 4),
	},
	"arm": {
		"unit_type": "object",
		"tags": ["abstract"],
		"tiling": 3,
		"text_type": 0,
		"layer": 15,
		"base_color": Vector2i(3, 1),
	},
	"text_arm": {
		"unit_type": "text",
		"tags": ["abstract"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(3, 1),
		"active_color": Vector2i(4, 2),
	},
	"bunny": {
		"unit_type": "object",
		"tags": ["animal", "forest"],
		"tiling": 2,
		"text_type": 0,
		"layer": 19,
		"base_color": Vector2i(0, 3),
	},
	"text_bunny": {
		"unit_type": "text",
		"tags": ["animal", "forest"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(0, 1),
		"active_color": Vector2i(0, 3),
	},
	"snail": {
		"unit_type": "object",
		"tags": ["animal", "forest"],
		"tiling": 0,
		"text_type": 0,
		"layer": 19,
		"base_color": Vector2i(6, 2),
	},
	"text_snail": {
		"unit_type": "text",
		"tags": ["animal", "forest"],
		"tiling": -1,
		"text_type": 0,
		"layer": 20,
		"base_color": Vector2i(6, 1),
		"active_color": Vector2i(6, 2),
	},
}

@export var level_size: Vector3i = Vector3i(5,5,5):
	set(to):
		level_size = to
		%LevelBounds.scale = Vector3(level_size)
		%LevelBounds.global_position = Vector3(level_size.x, -level_size.y, level_size.z)/2
@export var palette: Image = preload("res://Palettes/default.png")
@export var object_palette: Dictionary = {}
@export var object_to_pallete: String = ""
@export var add_object: bool:
	set(to):
		add_object = false
		var res = object_list[object_to_pallete].duplicate()
		res["sprite"] = object_to_pallete
		object_palette[object_to_pallete] = res
		object_to_pallete = ""
@export var add_objects_from_level: bool:
	set(to):
		add_objects_from_level = false
		for unit in %Units.get_children():
			var res = object_list[unit.unit_name].duplicate()
			res["sprite"] = unit.unit_name
			object_palette[unit.unit_name] = res

func _ready() -> void:
	%LevelBounds.scale = Vector3(level_size)
	%LevelBounds.global_position = Vector3(level_size.x, -level_size.y, level_size.z)/2
	if not Engine.is_editor_hint():
		Global.current_palette = palette
		Global.level = self
		%Camroot.global_position = Vector3(level_size.x, -level_size.y, level_size.z)/2
		%Enviroment.get_environment().background_color = Global.get_palette_color(Vector2i(1,0))
		%LevelBounds.get_active_material(0).albedo_color = Global.get_palette_color(Vector2i(0,4))
